### ISSUE TITLE
ストラトスフェアについての補足

### ISSUE THREAD

**Issue by Masaikirin** [Hitomi-San/cards#1]
### ストラスフェア
ストラスフェアの原文ルールはこちらになります。

[New Card Games](http://www.grimwold.org.uk/games/cards/index.php?game=Strato-Sphere)

**Comment by hmwakasa** [comment]
情報ありがとうございます。原文へのリンクを掲載しました。

まだ原文に目を通せていないので、原文に目を通し次第、必要があれば本文に加筆修正をします。

**Comment by hmwakasa** [comment]
原文に目を通し、本文に加筆を施しました。
